<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<Version>0.0.1</Version>
	<FileVersion>0.0.1</FileVersion>
	<UseWindowsForms>True</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NovaLingua.Lib\NovaLingua.Lib.csproj" />
  </ItemGroup>

</Project>
